# Template C++ Application

# This template allows you to validate your C++ application.
# The workflow allows running tests and code linting on the default branch.


image:
  name: plath/mercurydpm@sha256:0743f49b71776f9fc66444630306b505fb7c2104d1a8d55b9c1efbb1c7812250

pipelines:
  default:
      - step:
          name: Test
          script:
            - mkdir MercuryBuild
            - cd MercuryBuild
            - cmake -DCMAKE_BUILD_TYPE=Debug -DMercury_BUILD_USER_DIR=ON -G 'Unix Makefiles' ../
            - make fullTest
            - make doc
          artifacts:
            - error_log.txt
          after-script:
            - pipe: atlassian/slack-notify:2.0.0
              variables:
                WEBHOOK_URL: 'https://hooks.slack.com/services/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'
                PRETEXT: 'Checking commit; make fullTest running for $BITBUCKET_REPO_SLUG, branch: $BITBUCKET_BRANCH'
                MESSAGE: '"[${ENVIRONMENT_NAME}] build has exited with status $build_status; $([[ -s error_log.txt ]] && cat error_log.txt || echo All tests passed!)"'
                DEBUG: 'true'