# Template C++ Application

# This template allows you to validate your C++ application.
# The workflow allows running tests and code linting on the default branch.


image: gcc:10.2

pipelines:
  default:
      - step:
          name: Test
          script:
            - make fullTest
          artifacts:
            - error_log.txt
          after-script:
            - pipe: atlassian/slack-notify:2.0.0
              variables:
                WEBHOOK_URL: 'https://hooks.slack.com/services/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'
                PRETEXT: 'Checking commit; make fullTest running for $BITBUCKET_REPO_SLUG, branch: $BITBUCKET_BRANCH'
                MESSAGE: '"[${ENVIRONMENT_NAME}] build has exited with status $build_status; $([[ -s error_log.txt ]] && cat error_log.txt || echo All tests passed!)"'
                DEBUG: 'true'