FROM ubuntu  


# Install dependencies.
RUN apt-get update && \
     apt-get install -y \
     curl \
     sudo \
     zip \
     xz-utils \
     libx11-dev \
     libxi-dev \
     libxres-dev \
     libxt-dev \
     libxxf86vm-dev \
     libfontconfig1 \
     libxrender1 \
     libxtst-dev \
     libgl1-mesa-glx \
     gfortran \
     cmake \
     build-essential \
     g++ \
     git \
     openmpi-bin \
     mpi-default-dev \
     doxygen \
     graphviz \
     jq \
     less \
     python3
